# Generated by Django 5.2.12 on 2026-03-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('profile', models.CharField(default='Default', max_length=128)),
                ('url', models.URLField()),
            ],
        ),
    ]
